#+title: czm-lean4.el: Some embellishments for lean4-mode
#+author: Paul Nelson

* Overview
This package collects features that I'm using in conjunction with [[https://github.com/leanprover/lean4-mode][lean4-mode]].

1. Reasonable values for =beginning-of-defun-function= and =end-of-defun-function=, so that =beginning-of-defun= (=C-M-a=), =end-of-defun= (=C-M-e=) and =narrow-to-defun= (=C-x n d=) work.
2. Reasonable values for =outline-regexp= and =outline-level=, so that [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Outline-Mode.html][Outline mode]] works.
3. A command for displaying the active namespace/section/variable declarations.
4. (Taken from https://github.com/leanprover/lean4-mode/issues/22) A command for temporarily pausing the info display.
5. Commands for searching the appropriate Mathlib folder (via consult-ripgrep), either for all text or just theorem-like headings.
6. A command for inserting sections/namespaces, or wrapping a region with those.
7. A command for displaying the info buffer below the current window (rather than the default behavior, to the side - I often prefer one over the other).
8. Line wrapping for the goal window, with visual indicators where it wraps.
   

* Configuration
This package requires [[https://github.com/leanprover/lean4-mode][lean4-mode]], so install that first.

Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:
#+begin_src elisp
(use-package czm-lean4
  :after lean4-mode
  :hook (lean4-mode . czm-lean4-mode-hook)
  :hook (magit-section-mode . czm-lean4-magit-section-mode-hook)
  :bind (:map lean4-mode-map
              ("C-c v" . czm-lean4-show-variables)
              ("C-c C-p C-p" . czm-lean4-toggle-info-pause)
              ("C-c m m" . czm-lean4-search-mathlib)
              ("C-c m h" . czm-lean4-search-mathlib-headings)
              ("C-c C-o" . czm-lean4-toggle-info-split-below))
  :config
  (advice-add 'lean4-info-buffer-redisplay :around #'czm-lean4-info-buffer-redisplay))
#+end_src

Customize the binds as you like, and use the built-in documentation (=C-h f czm-lean4-whatever=) to see exactly what the commands do.

* More configuration
Here's the more complete configuration I'm using in conjunction with lean4-mode, which contains other tweaks that seemed best left out of this package.

#+begin_src elisp
(use-package lean4-mode
  :elpaca (:host github :repo "leanprover/lean4-mode"
                 :files ("*.el" "data"))
  :hook (lean4-mode . spout-mode)
  :commands (lean4-mode)
  :custom
  (lean4-keybinding-lean4-toggle-info (kbd "C-c C-y"))
  :config
  ;; disable annoying file watcher spam
  (setq lsp-enable-file-watchers nil)
  :defer t)

(use-package czm-lean4
  :elpaca (:host github :repo "ultronozm/czm-lean4.el"
                 :depth nil)
  :after lean4-mode
  :hook (lean4-mode . czm-lean4-mode-hook)
  :hook (magit-section-mode . czm-lean4-magit-section-mode-hook)
  :bind (:map lean4-mode-map
              ("C-c v" . czm-lean4-show-variables)
              ("C-c C-p C-p" . czm-lean4-toggle-info-pause)
              ("C-c C-m C-m" . czm-lean4-search-mathlib)
              ("C-c C-m C-h" . czm-lean4-search-mathlib-headings)
              ("C-c C-," . czm-lean4-insert-section-or-namespace)
              ("C-c C-i" . czm-lean4-toggle-info-split-below)
              ("C-c C-o" . czm-lean4-toggle-info-split-right))
  :custom
  (czm-lean4-info-window-height-fraction 0.4)
  (czm-lean4-info-window-width-fraction 0.4)
  :config
  (advice-add 'lean4-info-buffer-redisplay :around #'czm-lean4-info-buffer-redisplay))

;; by default, flycheck for lean4-mode causes the minibuffer to flicker.
;; the following code disables that.
(defun czm-flycheck-display-error-messages (errors)
  "Display ERRORS using `message'.
If major-mode is lean4-mode, then don't do anything."
  (unless (eq major-mode 'lean4-mode)
    (let ((message-truncate-lines t))
      (flycheck-display-error-messages errors))))
(setq flycheck-display-errors-function #'czm-flycheck-display-error-messages)

;; lsp-mode calculates line numbers without first calling widen.
;; let's fix that, so that line numbers work in narrowed buffers, too.
(defun my-lsp--cur-line (&optional point)
  (save-restriction
    (widen)
    (1- (line-number-at-pos point))))
(advice-add 'lsp--cur-line :override #'my-lsp--cur-line)

(use-package eldoc-box
  :commands (eldoc-box-help-at-point))

(global-set-key (kbd "C-c e") #'eldoc-box-help-at-point)
#+end_src
